[[keyboard.bindings]]
chars = "\u001Ba"
key = "A"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "B"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bc"
key = "C"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bd"
key = "D"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Be"
key = "E"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "F"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bg"
key = "G"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bh"
key = "H"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bi"
key = "I"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bj"
key = "J"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bk"
key = "K"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bl"
key = "L"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bm"
key = "M"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bn"
key = "N"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bo"
key = "O"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bp"
key = "P"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bq"
key = "Q"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Br"
key = "R"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bs"
key = "S"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bt"
key = "T"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bu"
key = "U"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bv"
key = "V"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bw"
key = "W"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bx"
key = "X"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001By"
key = "Y"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bz"
key = "Z"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B]"
key = "]"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B["
key = "["
mods = "Alt"
